const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const puppeteer = require('puppeteer');


const questionSchema = z.object({
  question: z.string(),
  intention: z.string(),
  answer: z.string(),
});


const interviewReportSchema = z.object({

  matchScore: z
    .number()
    .min(0)
    .max(100),

  technicalQuestions: z.array(
    questionSchema
  ),

  behavioralQuestions: z.array(
    questionSchema
  ),

  skillGaps: z.array(
    z.object({
      skill: z.string(),
      severity: z.enum([
        "low",
        "medium",
        "high"
      ]),
    })
  ),

  preparationPlan: z.array(
    z.object({
      day: z.number().int().positive(),
      focus: z.string(),
      tasks: z.array(
        z.string()
      ),
    })
  ),

  title: z.string()

});


async function generateInterviewReport(
  resume,
  selfdescribe,
  jobdescribe
) {

  if (!process.env.GOOGLE_GENAI_API_KEY) {
    throw new Error(
      "GOOGLE_GENAI_API_KEY is missing from the .env file."
    );
  }


  if (!resume || !jobdescribe) {
    throw new Error(
      "Resume and job description are required."
    );
  }


  const prompt = `
Generate an interview preparation report for this candidate.

Candidate resume:
${resume}


Candidate self-description:
${selfdescribe}


Job description:
${jobdescribe}


Return only JSON according to the schema.
`;


  const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY,
  });


  const response = await ai.models.generateContent({

    model:
      process.env.GEMINI_MODEL ||
      "gemini-3-flash-preview",

    contents: prompt,

    config: {
      responseMimeType: "application/json",

      responseJsonSchema:
        z.toJSONSchema(
          interviewReportSchema
        ),
    },
  });


  return interviewReportSchema.parse(
    JSON.parse(response.text)
  );

}

async function generatePdfFromHTML(htmlContent){
  // Accept optional options via a second argument (e.g., { scale: 0.85 })
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // Set a reasonable viewport to control layout/rendering
  await page.setViewport({ width: 1200, height: 800 });

  // Ensure styles are applied as on-screen
  await page.emulateMediaType('screen');

  // If the HTML doesn't declare page size via CSS, prefer the provided A4 size and margins
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

  const pdfBuffer = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: { top: '20mm', right: '12mm', bottom: '20mm', left: '12mm' },
    preferCSSPageSize: true,
    scale: 0.87,
  });

  await browser.close();
  return pdfBuffer;
}


// Sanitize and normalize resume HTML to help keep it to one page and fix common link issues
function sanitizeResumeHtml(html) {
  if (!html || typeof html !== 'string') return html;

  // Inject base CSS to constrain layout to an A4-like single page and reduce large gaps
  const baseStyle = `
    <style>
      @page { size: A4; margin: 15mm; }
      html,body { width:210mm; height:297mm; margin:0; padding:0; font-family: Arial, Helvetica, sans-serif; font-size:11px; line-height:1.15; color:#222; }
      * { box-sizing: border-box; }
      .resume-root { max-height: 267mm; overflow: hidden; }
      img { max-width: 100%; height: auto; display:block; }
      h1,h2,h3 { margin:0 0 6px; }
      p { margin:0 0 6px; }
      a { color: #0a66c2; text-decoration: none; }
      .no-break { page-break-inside: avoid; break-inside: avoid; }
    </style>
  `;



  return html;
}

async function generateResumePdf({resume,selfdescribe,jobdescribe}){
  if (!process.env.GOOGLE_GENAI_API_KEY) {
    throw new Error(
      "GOOGLE_GENAI_API_KEY is missing from the .env file."
    );
  }

  const resumePdfSchema = z.object({
    html: z.string().describe(
      "The HTML content of the resume which can be converted to PDF using any library like puppeteer"
    ),
  });
  const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY,
  });
  const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfdescribe}
                        Job Description: ${jobdescribe}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1 page long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `;

const response = await ai.models.generateContent({
  model:
      process.env.GEMINI_MODEL ||
      "gemini-3-flash-preview",

    contents: prompt,

    config: {
      responseMimeType: "application/json",

      responseJsonSchema: z.toJSONSchema(resumePdfSchema),
    },
  });

  const jsonContent = JSON.parse(response.text);

  // Validate and sanitize HTML
  const parsed = resumePdfSchema.parse(jsonContent);
  const sanitizedHtml = sanitizeResumeHtml(parsed.html);
  const pdfBuffer = await generatePdfFromHTML(sanitizedHtml);
  return pdfBuffer;
}




module.exports = {generateInterviewReport, generateResumePdf};